id: IA67E0308
ocr_import_info:
  timestamp: '2023-09-25T16:18:49.706188+00:00'
  batch_id: batch-5d9b
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-25 16:28:44.731754+00:00
last_modified: 2023-09-25 16:28:44.731761+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12026
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12026
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་བཞི་བརྒྱ་པའི་འགྲེལ་པ་ཚིག་དོན་གསལ་བ་དང་དབུ་མ་འཇུག་པའི་རྣམ་བཤད་དེ་ཉིད་གསལ་སྒྲོན།
  languages:
  - bo
  author: རེད་མདའ་བ་གཞོན་ནུ་བློ་གྲོས།
statistics:
  ocr_word_mean_confidence_index: 0.9679974625342607
  ocr_word_median_confidence_index: 0.9993447
bases:
  I1KG12037:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12037
      total_pages: 556
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12037.txt
    statistics:
      ocr_word_median_confidence_index: 0.9993447
      ocr_word_mean_confidence_index: 0.9679974625342607
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
